### PR TITLE
style: Added a new .rustfmt.toml file to the root, and ran 'cargo +nightly fmt --workspace'.

### PR DESCRIPTION
**Pull request by ckaran**
This is my own rust formatting style file, fixed to try to keep everything within 80 columns wide so that I can see multiple files side by side.  At this point, all trailing whitespace has been removed, every file ends with a newline, and all tabs have been converted to spaces.

### CODE REVIEW

**Comment by jneem** [comment]
Thanks for the PR! I agree that we need to be enforcing `rustfmt`, but I'm inclined to just keep the defaults rather than imposing a particular configuration. Actually, we could even add `rustfmt.toml` to `.gitignore`, so that it's easier for everyone to have their own preferred configuration locally.

**Comment by ckaran** [comment]
I appreciate what you're saying, but it may be better to add in a `.rustfmt.toml` file that is configured with the defaults than to let everyone do what they want.  The reason is that the `.rustfmt.toml` files follow a precedence order, searching within the crate for the `rustfmt.toml`, then within the user's home directory, (and I can't remember where else).  So, if I run `cargo fmt` and there is no `.rustfmt.toml` in the crate, then you'll always get PRs that have been formatted with my own default style.  By adding in a `.rustfmt.toml` file in the crate root, you can control what the eventual formatting will be.

As for *why* you want this, consider how hard it is to review PRs where there's one or two substantive lines... and a boatload of formatting changes.  Adding a `.rustfmt.toml` file is a way of saving your sanity.

**Comment by jneem** [comment]
Hm, I see. So I was imagining that someone with a different formatting preference would work locally with their own configuration, and then run `rustfmt` with the default config just before submitting. But are you saying that -- as someone with formatting preferences that differ from the default -- you would prefer to just work with the project's formatting config rather than going back and forth?

**Comment by ckaran** [comment]
Yes.  The issue is that I actually script a lot of my build stuff. Part of my scripts is that I run `cargo fmt` immediately before a build.  As a result, if there is no `.rustfmt.toml` file within the crate, I will put everything into my own format, and if I forget to revert to your format, I will make horribly large PRs.  By adding in a `.rustfmt.toml` file within the crate, we're following the crate's standards automatically, and don't need to do anything special.  Does that make sense?

**Comment by jneem** [comment]
Makes sense, thanks for all the explanations and sorry for being slow about this! I basically never change formatting defaults, so I'd never thought about these issues.

I've opened a new PR that just adds an empty .rustfmt.toml, so I'll close this one.

**Pull request closed without merging**
